#!/usr/bin/perl
# vim: ft=perl:fdm=marker:fmr=#<,#>:fen:et:sw=2:
use strict;
use warnings FATAL => 'all';
use vars     qw($VERSION);
use autodie  qw(:all);

use utf8;
use open qw(:std :utf8);

my $APP  = 'ordgen';
$VERSION = '0.001';

use Data::Dumper;

{
  package Data::Dumper;
  no strict 'vars';
  $Terse = $Indent = $Useqq = $Deparse = $Sortkeys = 1;
  $Quotekeys = 0;
}

my $words = './words.txt';

# kör programmet så här för att använda '-' som delimiter
# istället för sammansatta ord:
# $ perl ordgen -- -

my $delimiter = shift // '';

open(my $fh, '<', $words) or die $!;

my %map;
while(<$fh>) {
  chomp;

  # fixa dessa i ordlistan alexander. Saknar - eller ' ' som skiljetecken.
  next if /Porslinsanka|Rullstolskalas|Salongs|Tvättbj/;

  my ($k, $v) = split(/[- ]/, $_);
  $map{lc($k)} = lc($v);
}

for my $k(sort(keys(%map))) {
  printf "%s%s%s\n", $k, $delimiter,  $map{(keys %map)[rand keys %map]};
}



